version: //docker-compose version

services:
  # Backedn-API
  Face-Detector-API:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/Face-Detector-API
    environment:
      POSTGRES_URI: postgres://akindoju:123456@postgres:5432/face-detector-docker
    links:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/Face-Detector-API

  # Postgres
  postgres:
  environment:
    POSTGRES_USER: akindoju
    POSTGRES_PASSWORD: 123456
    POSTGRES_DB: face-detector-docker
    POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432:5432"
